# Find errors on this file with http://www.yamllint.com/

# A. Site Settings /SEO options
# Overall options for your site, would affect your site SEO
# Default values are explained
locale                  :     #default["en-US"] format language-TERRITORY , e.g fr, en-GB, es-MX, pt-BR
title                   : Rendiment    #default["repository_name"]
title_separator         :     #default [" | "]
subtitle                : Database Performance   #default [your-repository-tagline]  
description             : Rendiment aims to help the community to improve the performance of the databases, with a focus on MySQL and PostgreSQL #default [your-repository-tagline]
url                     :     #See baseurl - On Github Pages you may leave it blank - If you use CNAME use your domain
baseurl                 :     #On Github Pages you may leave it blank. Have a look to: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
words_per_minute        :     #default[200]
timezone                : America/New_York    #"Europe/Madrid ,see https://jekyllrb.com/docs/configuration/options/ and https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# SEO
og_image                :     #default[author.avatar (see below)] or [github-avatar]
#twitter_site            :     #Avoid @
author:
  name                  :  Daniel Guzman Burgos   # Name Surname Company
  avatar                :  https://github.com/nethalo.png   # Try a square file. Info: Your github avatar on https://github.com/[USERNAME].png
  location              :  "Colombia"   # New York, USA 
  links:                
    - url:  contact@rendiment.io #A link or email: https://twitter.com/jack, mail@example.com
      icon: fa-solid fa-envelope # A Fontawesome 5 code: fab fa-twitter - see https://fontawesome.com/
    - url: https://www.linkedin.com/in/danielmauricioguzman/
      icon: fab fa-linkedin
      label: LinkedIn
    - url: https://github.com/nethalo
      icon: fab fa-github
      label: GitHub
#    - url:  # Another link
#      icon: # Anothet FontAwesome code

# Web tracking - Google services https://analytics.google.com/analytics/web/
# gtag_id is the preferred option, see https://developers.google.com/analytics/devguides/collection/gtagjs/migration?hl=en
# analytics provided for backwards compatibility
gtag_id                 :  G-6MGB047ESJ
analytics_id            :  

# Search
search:
  provider: lunr
  label: Search
  landing_page: /search
  
# B. Navigation
# Configure your navbar and the footer of your site

# Navbar: 
#   "brand" options would be set on the left side of your navbar
#   "nav" would be set on the right side. Two-level nav links available
navbar:
  style     :  #default is the classical top navbar, set "fab" for a floating action button navbar or "dual"
  expand    :  # At which device size expand the navbar menu. default[md] https://getbootstrap.com/docs/4.5/layout/overview/
  brand:
    title   :  Rendiment # Title in navbar
    url     :  # default["url/baseurl"]
    img     :  # An small image, try 30x30px
  nav:
  - title   : Blog # Label
    url     : /blog/ # url	
#  - title   : Cheatsheets
#    url     : /cheatsheets
  - title   : Extras
    child   :
      - title : Tags
        url   : /tags
      - title : Categories
        url   : /categories
      - title : Archive
        url   : /archive
#  - title   : Docs
#    url     : https://dieghernan.github.io/chulapa/docs/01-install
#  - title   : # Label submenu
#    child:		
#    - title: # Child label		
#      url  : # child url	
#    - title: # Child label		
#      url  : # child url	
#Social links to be placed on your site footer
footer:
  links:
    - label : Repo on Github # Label
      icon  : fab fa-github # Fontawesome 5 icon
      url   : https://github.com/nethalo # A link or email: https://twitter.com/jack, mail@example.com
    - label: "RSS"
      icon: "fa fa-rss"
      url:  "/feed.xml"
  copyright: © Rendiment 2026 # default is © <year> <name> 
  
# C. Theme Settings
# Google Fonts https://fonts.google.com/, add as many as you need
googlefonts:
  - url : 'https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap'
  - url : 'https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap'

# D. Jekyll Defaults and collections: see https://jekyllrb.com/

# Blog pagination: on this site /blog/index.html. https://jekyllrb.com/docs/pagination/
paginate: 4
paginate_path: "/blog/page:num/"

# Collections https://jekyllrb.com/docs/step-by-step/09-collections/
#collections:
#  cheatsheet:
#    output: true
#    permalink: /cheatsheets/:name
#collections_dir     : 
#permalink           : /:year:month:day_:title/


# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      include_on_search   : false
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type       : "post"
      include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_related      : true
      show_bottomnavs   : true
      show_sociallinks  : true
      show_comments     : true
      show_tags         : true
      show_categories   : true
      show_author       : true
      show_breadcrumb   : true
      breadcrumb_list   :
        - label: Home
          url: /
        - label: Blog
          url: /blog/
#  -
#    scope:
#      path: ""
#      type: "cheatsheet"
#    values:
#      header_type       : "hero"
#      show_bottomnavs   : true
#      show_sociallinks  : true
#      include_on_search : true
#      show_breadcrumb   : true
#      breadcrumb_list   :
#        - label: Cheatsheets
#          url: /cheatsheets


# XX. Other settings - no need to modify
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed


# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor

include:
 - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

